// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5smG9tlrnAkomSUYPHwoIxsDAX7ka2U4',
    appId: '1:1074160726787:web:c8fd2eb3bb25589ce4ef36',
    messagingSenderId: '1074160726787',
    projectId: 'chatcourse-146a1',
    authDomain: 'chatcourse-146a1.firebaseapp.com',
    storageBucket: 'chatcourse-146a1.appspot.com',
    measurementId: 'G-W55N7KWYD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrGBOACLoiFjh6NRWwQtfrI0vhUJ1zock',
    appId: '1:1074160726787:android:09b9738f6a2d3eace4ef36',
    messagingSenderId: '1074160726787',
    projectId: 'chatcourse-146a1',
    storageBucket: 'chatcourse-146a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVJOlzKv4x5mS6Myz27vGPbLW1XG6pgzg',
    appId: '1:1074160726787:ios:b4103aa3220906dbe4ef36',
    messagingSenderId: '1074160726787',
    projectId: 'chatcourse-146a1',
    storageBucket: 'chatcourse-146a1.appspot.com',
    iosBundleId: 'com.example.chatTharwat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVJOlzKv4x5mS6Myz27vGPbLW1XG6pgzg',
    appId: '1:1074160726787:ios:b4103aa3220906dbe4ef36',
    messagingSenderId: '1074160726787',
    projectId: 'chatcourse-146a1',
    storageBucket: 'chatcourse-146a1.appspot.com',
    iosBundleId: 'com.example.chatTharwat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5smG9tlrnAkomSUYPHwoIxsDAX7ka2U4',
    appId: '1:1074160726787:web:c0cd5ecbe37f2b91e4ef36',
    messagingSenderId: '1074160726787',
    projectId: 'chatcourse-146a1',
    authDomain: 'chatcourse-146a1.firebaseapp.com',
    storageBucket: 'chatcourse-146a1.appspot.com',
    measurementId: 'G-NH984H7EWL',
  );

}